//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by E2Utility.rc
//
#define IDB_PNG1                        101
#define IDB_RECALLBAR                   102
#define IDB_PNG12                       103
#define IDB_PNG13                       104
#define IDB_PNG14                       105
#define IDB_PNG15                       106
#define Summoner_Dash                   107
#define Summoner_Dash_Cooldown          108
#define Summoner_Empty                  109
#define Summoner_Empty_Cooldown         110
#define Summoner_flashPerksHextechFlashtraption 111
#define Summoner_flashPerksHextechFlashtraption_Cooldown 112
#define Summoner_flashPerksHextechFlashtraptionBlue 113
#define Summoner_flashPerksHextechFlashtraptionBlue_Cooldown 114
#define Summoner_Mark                   115
#define Summoner_Mark_Cooldown          116
#define SummonerBarrier                 117
#define SummonerBarrier_Cooldown        118
#define SummonerBoost                   119
#define SummonerBoost_Cooldown          120
#define SummonerClairvoyance            121
#define SummonerClairvoyance_Cooldown   122
#define SummonerDot                     123
#define SummonerDot_Cooldown            124
#define SummonerExhaust                 125
#define SummonerExhaust_Cooldown        126
#define SummonerFlash                   127
#define SummonerFlash_Cooldown          128
#define SummonerFlashPerksHextechFlashtraptionV2 129
#define SummonerFlashPerksHextechFlashtraptionV2_Cooldown 130
#define SummonerHaste                   131
#define SummonerHaste_Cooldown          132
#define SummonerHeal                    133
#define SummonerHeal_Cooldown           134
#define SummonerMana                    135
#define SummonerMana_Cooldown           136
#define SummonerSmite                   137
#define SummonerSmite_Cooldown          138
#define SummonerSnowball                139
#define SummonerSnowball_Cooldown       140
#define SummonerTeleport                141
#define SummonerTeleport_Cooldown       142
#define TeleportCancel                  143
#define TeleportCancel_Cooldown         144
#define Aatrox                          145
#define Ahri                            146
#define Akali                           147
#define Alistar                         148
#define Amumu                           149
#define Anivia                          150
#define Annie                           151
#define Ashe                            152
#define AurelionSol                     153
#define Azir                            154
#define Bard                            155
#define Blitzcrank                      156
#define Brand                           157
#define Braum                           158
#define Caitlyn                         159
#define Camille                         160
#define Cassiopeia                      161
#define Chogath                         162
#define Corki                           163
#define Darius                          164
#define Default                         165
#define Diana                           166
#define Draven                          167
#define DrMundo                         168
#define Ekko                            169
#define Elise                           170
#define Evelynn                         171
#define Ezreal                          172
#define FiddleSticks                    173
#define Fiora                           174
#define Fizz                            175
#define Galio                           176
#define Gangplank                       177
#define Garen                           178
#define Gnar                            179
#define Gragas                          180
#define Graves                          181
#define Hecarim                         182
#define Heimerdinger                    183
#define Illaoi                          184
#define Irelia                          185
#define Ivern                           186
#define Janna                           187
#define JarvanIV                        188
#define Jax                             189
#define Jayce                           190
#define Jhin                            191
#define Jinx                            192
#define Kaisa                           193
#define Kalista                         194
#define Karma                           195
#define Karthus                         196
#define Kassadin                        197
#define Katarina                        198
#define Kayle                           199
#define Kayn                            200
#define Kennen                          201
#define Khazix                          202
#define Kindred                         203
#define Kled                            204
#define KogMaw                          205
#define Leblanc                         206
#define LeeSin                          207
#define Leona                           208
#define Lissandra                       209
#define Lucian                          210
#define Lulu                            211
#define Lux                             212
#define Malphite                        213
#define Malzahar                        214
#define Maokai                          215
#define MasterYi                        216
#define MissFortune                     217
#define MonkeyKing                      218
#define Mordekaiser                     219
#define Morgana                         220
#define Nami                            221
#define Nasus                           222
#define Nautilus                        223
#define Neeko                           224
#define Nidalee                         225
#define Nocturne                        226
#define Nunu                            227
#define Olaf                            228
#define Orianna                         229
#define Ornn                            230
#define Pantheon                        231
#define Poppy                           232
#define PracticeTool_TargetDummy        233
#define Pyke                            234
#define Quinn                           235
#define Rakan                           236
#define Rammus                          237
#define RekSai                          238
#define Renekton                        239
#define Rengar                          240
#define Riven                           241
#define Rumble                          242
#define Ryze                            243
#define Sejuani                         244
#define Shaco                           245
#define Shen                            246
#define Shyvana                         247
#define Singed                          248
#define Sion                            249
#define Sivir                           250
#define Skarner                         251
#define Sona                            252
#define Soraka                          253
#define Swain                           254
#define Sylas                           255
#define Syndra                          256
#define TahmKench                       257
#define Taliyah                         258
#define Talon                           259
#define Taric                           260
#define Teemo                           261
#define Thresh                          262
#define Tristana                        263
#define Trundle                         264
#define Tryndamere                      265
#define TwistedFate                     266
#define Twitch                          267
#define Udyr                            268
#define Urgot                           269
#define Varus                           270
#define Vayne                           271
#define Veigar                          272
#define Velkoz                          273
#define Vi                              274
#define Viktor                          275
#define Vladimir                        276
#define Volibear                        277
#define Warwick                         278
#define Xayah                           279
#define Xerath                          280
#define XinZhao                         281
#define Yasuo                           282
#define Yorick                          283
#define Zac                             284
#define Zed                             285
#define Ziggs                           286
#define Zilean                          287
#define Zoe                             288
#define Zyra                            289
#define SB_Default                      290
#define SB_HUD                          291
#define SB_Invisible                    292
#define SB_RecallAbort                  293
#define SB_RecallFinish                 294
#define SB_RecallStart                  295
#define SB_Ultimate                     296
#define SB_summonerbarrier              297
#define SB_summonerboost                298
#define SB_summonerdot                  299
#define SB_summonerexhaust              300
#define SB_summonerflash                301
#define SB_summonerhaste                302
#define SB_summonerheal                 303
#define SB_summonersmite                304
#define SB_summonerteleport             305
#define SB_SSInvisible                  306
#define CD_HudSelf                      307
#define LP_Aatrox                       308
#define LP_Ahri                         309
#define LP_Akali                        310
#define LP_Alistar                      311
#define LP_Amumu                        312
#define LP_Anivia                       313
#define LP_Annie                        314
#define LP_Ashe                         315
#define LP_AurelionSol                  316
#define LP_Azir                         317
#define LP_Bard                         318
#define LP_Blitzcrank                   319
#define LP_Brand                        320
#define LP_Braum                        321
#define LP_Caitlyn                      322
#define LP_Camille                      323
#define LP_Cassiopeia                   324
#define LP_Chogath                      325
#define LP_Corki                        326
#define LP_Darius                       327
#define LP_Default                      328
#define LP_Diana                        329
#define LP_Draven                       330
#define LP_DrMundo                      331
#define LP_Ekko                         332
#define LP_Elise                        333
#define LP_Evelynn                      334
#define LP_Ezreal                       335
#define LP_FiddleSticks                 336
#define LP_Fiora                        337
#define LP_Fizz                         338
#define LP_Galio                        339
#define LP_Gangplank                    340
#define LP_Garen                        341
#define LP_Gnar                         342
#define LP_Gragas                       343
#define LP_Graves                       344
#define LP_Hecarim                      345
#define LP_Heimerdinger                 346
#define LP_Illaoi                       347
#define LP_Irelia                       348
#define LP_Ivern                        349
#define LP_Janna                        350
#define LP_JarvanIV                     351
#define LP_Jax                          352
#define LP_Jayce                        353
#define LP_Jhin                         354
#define LP_Jinx                         355
#define LP_Kaisa                        356
#define LP_Kalista                      357
#define LP_Karma                        358
#define LP_Karthus                      359
#define LP_Kassadin                     360
#define LP_Katarina                     361
#define LP_Kayle                        362
#define LP_Kayn                         363
#define LP_Kennen                       364
#define LP_Khazix                       365
#define LP_Kindred                      366
#define LP_Kled                         367
#define LP_KogMaw                       368
#define LP_Leblanc                      369
#define LP_LeeSin                       370
#define LP_Leona                        371
#define LP_Lissandra                    372
#define LP_Lucian                       373
#define LP_Lulu                         374
#define LP_Lux                          375
#define LP_Malphite                     376
#define LP_Malzahar                     377
#define LP_Maokai                       378
#define LP_MasterYi                     379
#define LP_MissFortune                  380
#define LP_MonkeyKing                   381
#define LP_Mordekaiser                  382
#define LP_Morgana                      383
#define LP_Nami                         384
#define LP_Nasus                        385
#define LP_Nautilus                     386
#define LP_Neeko                        387
#define LP_Nidalee                      388
#define LP_Nocturne                     389
#define LP_Nunu                         390
#define LP_Olaf                         391
#define LP_Orianna                      392
#define LP_Ornn                         393
#define LP_Pantheon                     394
#define LP_Poppy                        395
#define LP_Pyke                         396
#define LP_Quinn                        397
#define LP_Rakan                        398
#define LP_Rammus                       399
#define LP_RekSai                       400
#define LP_Renekton                     401
#define LP_Rengar                       402
#define LP_Riven                        403
#define LP_Rumble                       404
#define LP_Ryze                         405
#define LP_Sejuani                      406
#define LP_Shaco                        407
#define LP_Shen                         408
#define LP_Shyvana                      409
#define LP_Singed                       410
#define LP_Sion                         411
#define LP_Sivir                        412
#define LP_Skarner                      413
#define LP_Sona                         414
#define LP_Soraka                       415
#define LP_Swain                        416
#define LP_Sylas                        417
#define LP_Syndra                       418
#define LP_TahmKench                    419
#define LP_Taliyah                      420
#define LP_Talon                        421
#define LP_Taric                        422
#define LP_Teemo                        423
#define LP_Thresh                       424
#define LP_Tristana                     425
#define LP_Trundle                      426
#define LP_Tryndamere                   427
#define LP_TwistedFate                  428
#define LP_Twitch                       429
#define LP_Udyr                         430
#define LP_Urgot                        431
#define LP_Varus                        432
#define LP_Vayne                        433
#define LP_Veigar                       434
#define LP_Velkoz                       435
#define LP_Vi                           436
#define LP_Viktor                       437
#define LP_Vladimir                     438
#define LP_Volibear                     439
#define LP_Warwick                      440
#define LP_Xayah                        441
#define LP_Xerath                       442
#define LP_XinZhao                      443
#define LP_Yasuo                        444
#define LP_Yorick                       445
#define LP_Zac                          446
#define LP_Zed                          447
#define LP_Ziggs                        448
#define LP_Zilean                       449
#define LP_Zoe                          450
#define LP_Zyra                         451
#define LP_DefaultMap                   452
#define LP_Teleport                     453
#define WT_Green                        454
#define WT_Pink                        455

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        456
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
