//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by E2Utility2.0.rc
//
#pragma once
#define WT_Green                        101
#define WT_Pink                         102
#define CD_HudSelf                      103
#define Summoner_Dash                   107
#define Summoner_Dash_Cooldown          108
#define Summoner_Empty                  109
#define Summoner_Empty_Cooldown         110
#define Summoner_flashPerksHextechFlashtraption 111
#define Summoner_flashPerksHextechFlashtraption_Cooldown 112
#define Summoner_flashPerksHextechFlashtraptionBlue 113
#define Summoner_flashPerksHextechFlashtraptionBlue_Cooldown 114
#define Summoner_Mark                   115
#define Summoner_Mark_Cooldown          116
#define SummonerBarrier                 117
#define SummonerBarrier_Cooldown        118
#define SummonerBoost                   119
#define SummonerBoost_Cooldown          120
#define SummonerClairvoyance            121
#define SummonerClairvoyance_Cooldown   122
#define SummonerDot                     123
#define SummonerDot_Cooldown            124
#define SummonerExhaust                 125
#define SummonerExhaust_Cooldown        126
#define SummonerFlash                   127
#define SummonerFlash_Cooldown          128
#define SummonerFlashPerksHextechFlashtraptionV2 129
#define SummonerFlashPerksHextechFlashtraptionV2_Cooldown 130
#define SummonerHaste                   131
#define SummonerHaste_Cooldown          132
#define SummonerHeal                    133
#define SummonerHeal_Cooldown           134
#define SummonerMana                    135
#define SummonerMana_Cooldown           136
#define SummonerSmite                   137
#define SummonerSmite_Cooldown          138
#define SummonerSnowball                139
#define SummonerSnowball_Cooldown       140
#define SummonerTeleport                141
#define SummonerTeleport_Cooldown       142
#define Aatrox                          145
#define Ahri                            146
#define Akali                           147
#define Alistar                         148
#define Amumu                           149
#define Anivia                          150
#define Annie                           151
#define Ashe                            152
#define AurelionSol                     153
#define Azir                            154
#define Bard                            155
#define Blitzcrank                      156
#define Brand                           157
#define Braum                           158
#define Caitlyn                         159
#define Camille                         160
#define Cassiopeia                      161
#define Chogath                         162
#define Corki                           163
#define Darius                          164
#define Default                         165
#define Diana                           166
#define Draven                          167
#define DrMundo                         168
#define Ekko                            169
#define Elise                           170
#define Evelynn                         171
#define Ezreal                          172
#define FiddleSticks                    173
#define Fiora                           174
#define Fizz                            175
#define Galio                           176
#define Gangplank                       177
#define Garen                           178
#define Gnar                            179
#define Gragas                          180
#define Graves                          181
#define Hecarim                         182
#define Heimerdinger                    183
#define Illaoi                          184
#define Irelia                          185
#define Ivern                           186
#define Janna                           187
#define JarvanIV                        188
#define Jax                             189
#define Jayce                           190
#define Jhin                            191
#define Jinx                            192
#define Kaisa                           193
#define Kalista                         194
#define Karma                           195
#define Karthus                         196
#define Kassadin                        197
#define Katarina                        198
#define Kayle                           199
#define Kayn                            200
#define Kennen                          201
#define Khazix                          202
#define Kindred                         203
#define Kled                            204
#define KogMaw                          205
#define Leblanc                         206
#define LeeSin                          207
#define Leona                           208
#define Lissandra                       209
#define Lucian                          210
#define Lulu                            211
#define Lux                             212
#define Malphite                        213
#define Malzahar                        214
#define Maokai                          215
#define MasterYi                        216
#define MissFortune                     217
#define MonkeyKing                      218
#define Mordekaiser                     219
#define Morgana                         220
#define Nami                            221
#define Nasus                           222
#define Nautilus                        223
#define Neeko                           224
#define Nidalee                         225
#define Nocturne                        226
#define Nunu                            227
#define Olaf                            228
#define Orianna                         229
#define Ornn                            230
#define Pantheon                        231
#define Poppy                           232
#define Pyke                            233
#define Quinn                           234
#define Rakan                           235
#define Rammus                          236
#define RekSai                          237
#define Renekton                        238
#define Rengar                          239
#define Riven                           240
#define Rumble                          241
#define Ryze                            242
#define Sejuani                         243
#define Shaco                           244
#define Shen                            245
#define Shyvana                         246
#define Singed                          247
#define Sion                            248
#define Sivir                           249
#define Skarner                         250
#define Sona                            251
#define Soraka                          252
#define Swain                           253
#define Sylas                           254
#define Syndra                          255
#define TahmKench                       256
#define Taliyah                         257
#define Talon                           258
#define Taric                           259
#define Teemo                           260
#define Thresh                          261
#define Tristana                        262
#define Trundle                         263
#define Tryndamere                      264
#define TwistedFate                     265
#define Twitch                          266
#define Udyr                            267
#define Urgot                           268
#define Varus                           269
#define Vayne                           270
#define Veigar                          271
#define Velkoz                          272
#define Vi                              273
#define Viktor                          274
#define Vladimir                        275
#define Volibear                        276
#define Warwick                         277
#define Xayah                           278
#define Xerath                          279
#define XinZhao                         280
#define Yasuo                           281
#define Yorick                          282
#define Zac                             283
#define Zed                             284
#define Ziggs                           285
#define Zilean                          286
#define Zoe                             287
#define Zyra                            288
#define PracticeTool_TargetDummy        289
#define SB_Default                      290
#define SB_HUD                          291
#define SB_Invisible                    292
#define SB_RecallAbort                  293
#define SB_RecallFinish                 294
#define SB_RecallStart                  295
#define SB_Ultimate                     296
#define SB_summonerbarrier              297
#define SB_summonerboost                298
#define SB_summonerdot                  299
#define SB_summonerexhaust              300
#define SB_summonerflash                301
#define SB_summonerhaste                302
#define SB_summonerheal                 303
#define SB_summonersmite                304
#define SB_summonerteleport             305
#define SB_SSInvisible                  306

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        321
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
